"""empty message

Revision ID: 676c93eff547
Revises: 
Create Date: 2024-07-01 01:22:14.060377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676c93eff547'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('billing_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_load', sa.Boolean(), nullable=False),
    sa.Column('last_line_processed', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_file_hash'), 'billing_file', ['hash'], unique=True)
    op.create_index(op.f('ix_billing_file_id'), 'billing_file', ['id'], unique=False)
    op.create_table('bank_slip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('government_id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('debt_amount', sa.Float(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('billing_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['billing_file_id'], ['billing_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('debt_id'),
    sa.UniqueConstraint('government_id')
    )
    op.create_index(op.f('ix_bank_slip_hash'), 'bank_slip', ['hash'], unique=True)
    op.create_index(op.f('ix_bank_slip_id'), 'bank_slip', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_slip_id'), table_name='bank_slip')
    op.drop_index(op.f('ix_bank_slip_hash'), table_name='bank_slip')
    op.drop_table('bank_slip')
    op.drop_index(op.f('ix_billing_file_id'), table_name='billing_file')
    op.drop_index(op.f('ix_billing_file_hash'), table_name='billing_file')
    op.drop_table('billing_file')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
